services:
  api:
    build:
      context: ./apps/api
    env_file:
      - ./.env
    environment:
      DJANGO_DB_ENGINE: ${DJANGO_DB_ENGINE}
      DJANGO_DB_NAME: ${DJANGO_DB_NAME}
      DJANGO_DB_USER: ${DJANGO_DB_USER}
      DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
      DJANGO_DB_HOST: ${DJANGO_DB_HOST}
      DJANGO_DB_PORT: ${DJANGO_DB_PORT}
      DJANGO_DB_CONN_MAX_AGE: ${DJANGO_DB_CONN_MAX_AGE}
      DJANGO_SECURE: ${DJANGO_SECURE}
      USE_X_FORWARDED_HOST: ${USE_X_FORWARDED_HOST}
      DJANGO_USE_PROXY_SSL_HEADER: ${DJANGO_USE_PROXY_SSL_HEADER}
      DJANGO_DEBUG: "1"
    volumes:
      - ./apps/api:/app
      - api_data:/data
      - api_static:/app/staticfiles
    ports:
      - "8000:8000"
    entrypoint:
      - /bin/sh
      - -c
      - |
          set -e
          python manage.py migrate --noinput
          python manage.py runserver 0.0.0.0:8000
    networks:
      shared-net:
        aliases:
          - api

  web:
    build:
      context: ./apps/web
    env_file:
      - ./.env
    environment:
      NODE_ENV: "development"
      NPM_CONFIG_PRODUCTION: "false"
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:8000"
      BACKEND_API_URL: "http://api:8000"
      NEXT_TELEMETRY_DISABLED: "1"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    depends_on:
      - api
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"
    volumes:
      - ./apps/web:/app
      - web_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      shared-net:
        aliases:
          - web

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - api
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - api_static:/var/www/static:ro
    networks:
      - shared-net

volumes:
  api_data:
  api_static:
  web_node_modules:

networks:
  shared-net:
    external: true
    name: shared-net
